### ISSUE TITLE
Test and document variable dynamic configuration

### ISSUE THREAD

**Issue by invisibleroads** [crosscompute/crosscompute#105]
```
  variables:
    - id: output
      view: link
      path: output
```
```
        with open(output_folder + '/output', "wt") as text_file:
            text_file.write(text)
        with open(output_folder + '/output.json', "wt") as text_file:
            json.dump({'link-text': 'yabba', 'file-name': 'dabba'}, 
```
