### ISSUE TITLE
Consider whether to handle private dependencies in podman engine

### ISSUE THREAD

**Issue by invisibleroads** [crosscompute/crosscompute#112]

**Comment by invisibleroads** [comment]
We might have to support a combination of private servers, deploy keys and machine users. I don't think we should read anything directly from disk. Deploy keys probably cover most cases, though inconvenient.

Although I like the cleanliness of machine users, the fact that "collaborators" can write to personal repositories will be off-putting.

I think read only deploy keys will be the safest default.

**Comment by invisibleroads** [comment]
For repositories with public visibility, one can use the zip trick:

```
environment:                                                                                                                                      
  packages:                                                                                                                                       
    - id: pandas                                                                                                                                  
      manager: pip                                                                                                                                
    - id: crosscompute_macros[shapely]@https://github.com/crosscompute/crosscompute-macros/archive/refs/heads/main.zip                              
      manager: pip 
```

References
- https://stackoverflow.com/a/50192006
- https://stackoverflow.com/a/76620421
