### ISSUE TITLE
Consider making dataset reference folder if it does not exist

### ISSUE THREAD

**Issue by invisibleroads** [crosscompute/crosscompute#78]
```
could not find dataset reference ../make-safety-checklist/runs in 
~/Projects/crosscompute-content/lineworker-safety-guides/see-safety-logs/automate.yml
```

```
datasets:
  - folder: datasets/jobs
    reference:
      folder: ../make-safety-checklist/runs
  - folder: datasets/briefings
    reference:
      folder: ../log-safety-briefing/runs
```
