### ISSUE TITLE
Consider more concise syntax for datasets configuration

### ISSUE THREAD

**Issue by invisibleroads** [crosscompute/crosscompute#96]
```
datasets:
  - target: datasets/statistics.csv
    source: datasets/2023-statistics.csv

datasets:
  - target_path: datasets/statistics.csv
    source_path: datasets/2023-statistics.csv

datasets:
  - path: datasets/statistics.csv
    link: datasets/2023-statistics.csv
```
